src/megachatapi_impl.cpp
src/megachatapi_impl.h

No need to use MegaApi to get the file attribute of the node, it's
already included in the MegaNode.

Avoid dependency of MegaApi

---

src/chatd.cpp

Change the key when a user leaves, so even if he rejoins and access to
messages that were sent when he didn't participate, he won't be able to
decrypt them.

Rotate key upon user's leave

---

src/megachatapi_impl.cpp

During a short period of time, Webclient sent the nodekey as `key`
instead of `k`.

Provide backwards compatibility for attachment JSON

---

src/chatClient.cpp

Tests to perform:
- User A is a contact of User B and both participate on groupchat1. User A removes B, but still sees status of B in groupchat1.
- User B cancels his account, User A sends `DELPEER` for that user and removes the `Contact` object.

Keep subscribed to presence for non-contacts participating on groupchats

---

src/chatd.cpp
src/presenced.cpp

If the `ws_connect()` fails, `libws` will call `websockCloseCb()` and the `checkLibwsCall()` will throw an exception, resulting on the `.fail()` handler --> two managements of the same error.

Fix duplicated error-management

---

src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/presenced.cpp
tests/sdk_test/sdk_test.cpp
tests/sdk_test/sdk_test.h

This pull request resets `mTsLastPingSent` and `mTsLastRecv` when the heartbeat is enabled. When a connection fails and there is a reconnect some time later, `mTsLastPingSent` causes a reconnect loop if the last keepalive sent for the previous connection was more than 15 seconds ago.
`mTsLastRecv` is reset just for consistency and to not send the first keepalive immediately after a connection.
Some tests were also randomly failing because they weren't waiting for the chatrooms to be connected and ready to receive new messages. This pull requests adds a new getter to `MegaChatRoom` that allows tests to know when the chat is ready and continue.

Fix heartbeat and tests

---

src/chatd.cpp
src/chatd.h
src/presenced.cpp

There are certain operations that should not be performed until chatd connection is logged in (sent `JOIN`), but it wasn't enforced.
This branch also prevents resolution of promises already resolved.

Check the chatd is logged in

---

src/chatClient.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
tests/sdk_test/sdk_test.cpp

When the SDK is logged out or an ESID is received for any type of SDK request, automatically set the status of karere to "invalid session id", which results in a logout() from karere.

Management of invalid session

---

tests/sdk_test/sdk_test.cpp

after leaving a chatroom and rejoining it, the chatd connection must be
established. Otherwise, the test may fail.

Ensure chatd is connected

---

src/chatClient.cpp
src/chatd.cpp
src/chatd.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
tests/sdk_test/sdk_test.cpp

Previously RECEIVED command was sent for all new and old messages. Now, RECEIVED command is not sent while system is fetching and it is sent only once after received HISTDONE. It is never sent for a group-chat. For the rest of cases it is sent like before.

Control best moment to send RECEIVED command

---

bindings/Objective-C/MEGAChatSdk.h
src/chatClient.cpp
src/contactList.h
src/megachatapi.h
src/megachatapi_impl.cpp
src/presenced.cpp
src/presenced.h

Minor fixes to not become offline upon connection loss, but to keep the previous seen status. It also initializes to invalid value, so apps don't show status until received from server.

Improvements for presence status

---

src/chatd.cpp

I will consider if it's worthy to remove the logged in state of `Connection` and manage such state at the `chat::Client` level.

Join also chatrooms when connection is already logged in

---

src/chatd.cpp

In order to send a JOINRANGEHIST, the connection can be in state
connected but also in state logged in.

Adjust assert

---

src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h

Android provides background services that require to be connected to
chatd, but sending KEEPALIVEAWAY in order to tell chatd the user is
actually away

Allow to connect as the user is away from app

---

src/chatClient.cpp
tests/sdk_test/sdk_test.cpp

When the SDK fully disconnects and resets its connections, MEGAchat
should follow it and reconnect creating new sockets (and resolving DNS)

Reconnect triggered by SDK

---

src/chatd.cpp

When the last message in history is the one that is updated, it's still notified even if not loaded yet. This commit aims to fix that

Avoid notifications of message that haven't been loaded by the app

---

src/base/promise.h
src/sdkApi.h
tests/sdk_test/sdk_test.cpp

When a `MyMegaApi` is deleted, but there's a `MyListener` registered for a pending request, the `onRequestFinish()` will be executed anyway, resolving the associated promise. The resolution of the promise could create side-effects in other places. Better to do nothing if the instance of `MyMegaApi` has been deleted already.

Ignore completion of requests for deleted MegaApi instances

---

src/megachatapi_impl.cpp

`Client::setPresence()` returns a promise. Not registering a promise
handler for success is fine, but missing handler for failure results in
an exception of unhandled failed promise.

Fix set presence while no Internet connection

---

src/chatClient.cpp

We observed a crash in Jenkins that points to this .then handler
executed after the Client, which would mislead Sqlite to report out-of-
memory due to an invalid DB object.

Protection against deleted `Client`

---

src/chatd.cpp
src/chatdDb.h
src/chatdICrypto.h
src/chatdMsg.h
src/megachatapi.h
src/strongvelope/strongvelope.cpp
src/strongvelope/strongvelope.h

For new messages that are sent along with new keys, the `keyid` is set to
`CHATD_KEYID_INVALID` and it's never updated to its final `keyid`. Fixed!
Additionally, allow first message in sending queue to be the edition of an already confirmed message, not restrict it to a new message.
Also, reuse the `ts` of a `NEWMSG` for the `MSGUPDX`, which was updated (only in cache)

Fixes for sending queue

---

src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h
tests/sdk_test/sdk_test.cpp
tests/sdk_test/sdk_test.h

- Solve a collision over same chat
- At test, reject incoming call when there is another call in-progress (it's possible uncomment a piece of code and hangup existing call and answer new call)

Improve behavior when system has a call collision

---

src/sdkApi.h

If MegaChatApi has been deleted and the app logs out from MegaApi, but
there are pending requests to MegaApi, MegaApi will call
onRequestFinish() with EACCESS for each pending request, which will
attempt to queue the marshallCall on a deleted MegaChatApi (aka. `appCtx`).

Protect MyListener

---

src/chatClient.cpp
src/megachatapi_impl.cpp

During termination (logout), karere `disconnect()`, which results on a
notification of the online presence right before the logout finishes.
The app attempts to access to the `mClient` at the
`onChatOnlineStatusUpdate()` callback, but due to the thread's
switching, it's too late and the `mClient` is already invalid.
This fix solves the issue by not notifying the invalid presence as
result of disconnect during termination.

Skip presence's notification at termination

---

src/chatd.cpp

It could happen that the connection state changes since it was checked,
and `requestHistoryFromServer()` must be called exclusively while
online.

Move condition inside the marshal call

---

src/chatd.cpp
src/chatd.h

A message can be deleted by `postMsgToSending()` in the event our user has no-write-access or the message is too old. In that case, the message is moved into the manual-sending-queue. The intermediate layer immediately deletes the object, which turns the pointer to the message into invalid (and cannot be used for last-
message-stuff).
Furthermore, the `mSending` queue *does* change, since we delete items upon sending
when we know we won't be able to send them, like no write access or message is too old, so the assertion is failed in those cases.

Fix issue moving msgs to manual sending queue

---

src/chatClient.cpp

It may happen the SDK doesn't receive any data from server during 10 minutes, so for safety reasons it reconnects to API. That event is notified to MEGAchat, that may have its connections up and running and the user may have an ongoing call. In that case, we don't want to force a reconnect, since obviously the connection is alive due to the call.

Skip reconnect event from SDK while there is a call in progress

---

src/chatd.cpp
src/chatd.h

Messages used to be encrypted only once when they were added to the send
queue (and stored encrypted as blobs in the db), so the assumption was
that all messages in the send queue precede the one for which back
references are created. Now messages from the send queue are encrypted
just prior to sending, and if a send queue flush is retried, the
assumption that encrypted message is the last one is no longer true.

Fix creation of backrefs

---

src/chatClient.cpp

In case a new peer join is received first from chatd than from API, the new peer is notified but it was never saved to DB, since upon notificatio from API, the peer was already part of the groupchat. Once the app restarts, the peer was not anymore in the list of peers.

Persist new peers from chatd

---

src/rtcModule/webrtcAdapter.cpp

- Selects the default front camera by id (com.apple.avfoundation.avcapturedevice.built-in_video:1)
- Solves a bug in some languages that didn't include "front" in the description of the front camera

Fix front camera selection for iOS

---

src/megachatapi.h
src/megachatapi_impl.cpp

If the session expires, the app may access MEGAchat while the client is being destroyed. This commit aims to protect against those cases.

Protect MegaChatApi against client being terminated

---

src/megachatapi.h

The presence status actually use the lower 4 bits of a single byte, but it may contain flags in the higher 4 bits. Hence, to get the status, a flag mask is applied to the presence's value, `~0xF0`. As a result, the invalid presence is `0x0F` instead of `0xFF`.

Adjust code for invalid presence

---

src/rtcModule/streamPlayer.h
src/rtcModule/webrtc.cpp

Check video flags at StreamPlayer to avoid notify video frames when video is disabled. If webrtc update the protocol to disable audio/video flow in a session, this commit has to be removed

Check video flags at StreamPlayer to avoid notify video frames when video is disabled

---

src/chatd.cpp

The message could be already confirmed by server. It's better to send it
and receive the `REJECT` than to move it to the manual-sending-queue
directly, because if the server confirmed the message, we may end up
with the message in the history and the same message in the manual-
sending-queue.
By resending the message, if already confirmed, we will receive a `MSGID` and we can discard the message in the sending status safely.

Do not decide locally to move message to manual-sending

---

src/chatd.cpp

The last message can be a message in sending status or already confirmed
by server. The check used to assume the last-message was always
confirmed, which is wrong and triggers an assertion.

Check if last message needs update upon removal of manual-sending msg

---

src/chatd.cpp
src/chatd.h
src/chatdDb.h

When the app resumes a session and has all history (until the start of the history) in cache, a wrong initialization makes MEGAchat think it doesn't have it. This PR fixes that bug.

Fix last message when no connection

---

src/chatd.cpp
src/chatd.h

Rejection of messages are handled at other level nowadays. This obsolete
function does nothing due to the value of `mustBeInSending`. In the
coming weeks we may need to implement a reject for differnt op-codes.

Clean up obsolete code

---

src/base/logger.cpp

The list of registered loggers is static and its accesses must be
thread-safe. A `LockGuard` is used to guarantize the concurrent access
to the list of loggers upon addition/removal, but not for the `log()`
itself, which iterates through every registered logger.

Protect access to `mUserLoggers` upon usage

---

src/megachatapi_impl.cpp

For video files, the preview/thumbnail are set by the app and may not be
already set at the time node is checked to prepare the attachment.
However, the mediainfo (that is used to show the duration of the video)
in already available, so better to always attach the `fileattrstring`
when available.

Add mediainfo to attachment messages

---

src/chatClient.cpp

We have detected `Contact` objects being NULL, resulting in a segmentation fault. It could be due to the asignment of the Contact to the corresponding item in the ContactList map through a reference.

Adjust creation of Contact objects

---

src/IGui.h
src/chatClient.cpp
src/chatd.cpp
src/megachatapi_impl.cpp
src/megachatapi_impl.h

The callback `notifyInvited()` provides the same information (actually
less detailed) than the corresponding `addGroupChatItem()` and
`addPeerChatItem()`. Keeping such callback will result on duplicated
callbacks for the same event.

Fix notification of new chatroom

---

examples/qt/mainwindow.cpp

This function is now overloaded in the SDK (`inviteContact()`) and
without the proper type-casting, the compiler fails to find the
corresponding definition.

Fix compilation issue

---

src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h

There was a bug managing listeners registered by the app, `MegaChatRoomListener`. All of them were called when a new event happened in any of the opened chatrooms. This commit associates the listeners to the corresponding handler in order to fix it.

 Move management of MegaChatRoomListener to MegaChatRoomHandler 

---

src/base/logger.cpp
src/base/logger.h

There are crashes reported by iOS team at the `Logger::logString()`,
which we recently found it was not protected against access from
different threads. Now it's protected, but there are other unprotected
accesses that this commit aims to solve.

Enforce critical section for logger

---

src/megachatapi_impl.cpp
src/megachatapi_impl.h

`MegaChatApi` is not a base of `MegaChatApiImpl`, so the type-casting is
not suitable to notify the instance triggering the callback. Automated
tests noticed the instance was incorrect

Fix casting to MegaChatApi for callbacks from MegaChatRoomHandler

---

src/strongvelope/strongvelope.cpp

A user who is alone in a chatroom can still send new messages and post
new keys

Remove unnecessary assertion

---

src/chatd.cpp
src/chatd.h
src/chatdICrypto.h
src/strongvelope/strongvelope.cpp
src/strongvelope/strongvelope.h

This commit solves the situation when the client attempts to send a
`NEWKEY`+`NEWMSG`, but both are rejected. The key, however, is kept as
unconfirmed, so if later the user has privileges to send a `NEWMSG`, it
will not send a `NEWKEY`, but expects a confirmed keyid already.
We need to reset the current keyid if it's unconfirmed and got rejected.

Support for `REJECT` for `NEWKEY`

---

src/chatClient.cpp

When MEGAchat is initialized without `sid`, the instantiation of the
user-attribute cache (`mUserAttrCache`) is delayed until the completion
of fetchnodes. However, the registration of the `MegaGlobalListener` may
result on calls to `onUsersUpdate()` earlier than the initialization is
done, resulting on segmentation fault.

Fix a crash due to illegal access to user-attribute cache

---

src/chatd.cpp
src/chatd.h

In case chatd rejects a `HIST` opcode, disable the chatroom

Add support for reject of hist

---

src/chatd.cpp

Just in case the resolution of the promise executes callbacks and, in
the meantime, the timer expires.

Resolve promise after cancel timeout

---

src/chatd.cpp
src/chatd.h
src/chatdMsg.h
src/megachatapi.h
src/megachatapi_impl.cpp

The connection used to allow a logged-in state, established when the first chat completes its login. It's semantically wrong, since the connection is shared by multiple chats and it may happen that not all of
them are already logged in.
This commit resolves the `Connection::mLoginPromise` only when all chats are logged in and removes the (incorrect) state `Connection::State::kStateLoggedIn`.

Fix connection state

---

src/chatd.cpp

Android reported a bug when app is started in offline mode and the
history of a chat is fetched. MEGAchat, once all the history is loaded
in RAM and retrieved by the app, it never calls `onHistoryDone()`
because of the unexpected `nextSource == kHistSourceServerOffline`, so
the app keeps waiting forever for the corresponding
`onMessageLoaded(NULL)`.

Fix loading conversations in offline mode

---

src/chatd.cpp
src/strongvelope/strongvelope.cpp

It allows to decode the unknown type in future attempts once the
MEGAchat adds support.

Add pre-support for unknown types of mng messages

---

tests/sdk_test/sdk_test.cpp

It has been necessary add a `sleep` to allow execute the two listeners (MegaChatApi and MegaChatApiTest) for MegaRequest::TYPE_GET_ATTR_USER before exit from `MegaChatApiTest::changeLastName`.
In other case, we could ask for the name to MegaChatApi before this will be established because MegachatApiTest listener is called before than MegaChatApi listener

Solve problem at test ChangeMyOwnName

---

src/chatd.cpp

When the app starts in offline mode, connections to chatd are kept in
state `kStateNew`. That state must be preserved until the app requests
to connect, when MEGAchat retrieves the URLs of shards.
The `ECHO` mechanism, if used during offline mode, would set the state
to `kStateDisconnected`, preventing to get the URL.

Avoid to change the state of connection in offline mode

---

bindings/java/nz/mega/sdk/MegaChatApiJava.java
src/chatd.cpp
src/chatd.h
src/chatdMsg.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/presenced.cpp

Android app requests `MEGAchat::setBackgroundStatus(false) repeatedly while it's in foreground (every 3 secs), which may trigger a reconnect once and again when it's not needed.

 Avoid to start ECHO if already in foreground 

---

src/megachatapi_impl.cpp

Convert uint8_t to uint32_t for correct conversion to std::string

Correct conversión to std::string from end Call termCode

---

examples/qtmegachatapi/MainWindow.cpp

We have forgotten to replace MEGACHAT_INVALID_HANDLE by our own handle in this case

Replace invalid handle by own handle

---

src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h

Adjust native behaviour to webClient behaviour. This change had been apply to gropuCall branch but it has been moved to this branch before merging groupCall functionality because it was necessary to get compatibility between clients

Send CALLDATA with end-call always that is necessary

---

src/chatClient.cpp
src/karereCommon.cpp

This commit will clear any cached history for any chat, so it requires
to be freshly fetched from chatd. It will solve the issue of missing
management messages for the call-history while the client used protocol
version `/1`

Clear history of cached chats if DB version is out of date

---

src/chatd.cpp
src/chatdMsg.h

It may happen that a `NEWKEY keyxid`+[`NEWMSG msgxid keyxid`]* is received and confirmed by server, but the client only receive the key's confirmation (`NEWKEYID`, but not the `NEWMSGID`). Hence, upon reconnection, MEGAchat will resend the `NEWMSG msgxid keyxid` without a `NEWKEY`, which is not acceptable for chatd.
This branch attempts to fix the aforementioned scenario by updating the `keyxid` of unconfirmed messages and immediately set the `keyid` (both in sending item and in DB).

Update keyid of unconfirmed messages upon key's confirmation

---

src/chatd.cpp
src/chatd.h
src/net/libwebsocketsIO.cpp
src/net/libwebsocketsIO.h
src/net/libwsIO.cpp
src/net/libwsIO.h
src/net/websocketsIO.cpp
src/net/websocketsIO.h
src/presenced.cpp
src/presenced.h

In order to speed up the connection establishment to chatd/presenced, this branch adds a in-memory cache for resolved hostnames.
Any reconnection attempt automatically uses cached IPs and perform a DNS lookup in parallel. When the DNS is resolved, if the IPs don't match, it forces a reconnect directly (even if connected).

DNS cache for presenced and chatd

---

src/chatdMsg.h

Management messages don't have a `backRefId`, but it was not
initialized. Hence, it was used to verify the order and it generates
errors when it should not.

Fix error at message order verification

---

src/chatd.cpp
src/chatdMsg.h

Before parsing a string to check if it is a rich link, remove unnecessary last characters ('.', ',', ';', ':', ...)

Remove unnecessary last characters at rich link

---

src/chatd.cpp
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h
src/rtcModule/webrtcPrivate.h

UserA and UserB are in a call (state in-progress) and UserA gets disconnected. UserB receives a command indicating that UserA is off-line and he finishes the call but UserA follows in the call forever (until he hangs up the call). 
This PR solves this issue. When system detects that the connection is broken, it destroys all calls

 Destroy calls after disconnect

---

src/megachatapi.h
src/megachatapi_impl.cpp

Termination code from end call message is translated from one type to other type at UI level.
Conversion:
- A call with termination code END_CALL_REASON_CANCELLED will be converted to END_CALL_REASON_NO_ANSWER
- A call with duration > 0 and termination code END_CALL_REASON_ENDED or END_CALL_REASON_FAILED will be converted to END_CALL_REASON_ENDED
- A call with duration == 0 and termination code END_CALL_REASON_ENDED or END_CALL_REASON_FAILED will be converted to END_CALL_REASON_FAILED

Adjust termination code for end call message

---

src/megachatapi_impl.cpp
src/megachatapi_impl.h

Fix a bug with last message and end call message. Last message was not update with correct value at PR #372

Update last message content with correct termination code for end call message

---

src/chatd.cpp

If a message is not confirmed, it should always be editable/deletable,
since the message is never too old

Allow to edit unconfirmed messages

---

examples/qt/chatWindow.cpp
examples/qt/mainwindow.cpp
examples/qt/mainwindow.h
src/IGui.h
src/base/logger.h
src/base/promise.h
src/buffer.h
src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h
src/chatdICrypto.h
src/karereCommon.cpp
src/megachatapi.cpp
src/megachatapi_impl.cpp
src/presenced.cpp
src/presenced.h
src/rtcModule/IVideoRenderer.h
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h
src/sdkApi.h
src/strongvelope/strongvelope.cpp
src/userAttrCache.cpp
src/userAttrCache.h

- Clean warnings related to unused params.
- Clean warnings related to comparisions between different types: enums
with integers and similar.
- Remove unused methods.
- Refactoring of some members, like `client` --> `mKarereClient` and
similar.
- Fix wrong order of initialization list of members in `ChatClient`.
- Reorder of members in `ChatClient`

Clean warnings and refactoring

---

src/chatClient.cpp

When callback for fetchnodes completion is received by MEGAchat, in case
it's a new session (or there's no cache for MEGAchat), the resumption of
actionpackets must not happen until the MEGAchat client is fully
initialized. However, the `initWithNewSession()` is asynchronous and it
means that updates from actionpackets may happen before the engine is
fully initialized.
This commit solves the issue and the eventually failed assertion
`assert(mContactsLoaded)` in the callback `onChatsUpdate()`, which was
called as soon as there are pending APs received right after the
fetchnodes, while MEGAchat is fetching own keys.

Fix race-condition loading contacts

---

platforms/android/env-android.sh
src/chatClient.cpp
src/chatClient.h
src/chatdDb.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/net/libwsIO.cpp
src/presenced.h
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h
src/rtcModule/webrtcPrivate.h

Testing this branch it seems that WebRTC notifies the same status more than once. It may need adjustments to avoid so.
Steps: 
- User A starts a groupcall
- User B launches the app and gets notified about the groupcall as user not present, but more than once.

Notify when a call is in progress

---

src/chatd.cpp
src/strongvelope/strongvelope.h

Management messages are created by server and, therefore, they are not
client-side encrypted. They don't include any `backrefid`, so they
shouldn't be used to prepare the array of `backrefids` that are later
used to verification of the order.
In order to send the event when a msg order tampering is detected, we need the SDK branch `feature/new-event-types` (https://github.com/meganz/sdk/pull/1140)

Avoid to consider management msgs for backrefids

---

src/chatd.cpp
src/chatd.h
src/chatdMsg.h

chatd v4 acknowledges the seen pointer when set, or responds with the updated seen pointer if newer.
chatd v3 sends a CALLTIME when there's a groupcall in-progress. Need to consume those bytes from the buffer.

Update chatd protocol

---

src/chatd.cpp
src/chatd.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h
src/rtcModule/webrtcPrivate.h

- Manage termination code kErrNotSupported. It's returned when client doesn't manage webrtc
- Destroy call handler when we finish a call and we are the last participant. Avoid maintain alive a MegaChatCallHandler if we don't receive a ' ENDCALL'  command (lost connection or we are unique participant at chat room)

 Manage termination code kErrNotSupported

---

src/chatClient.cpp

When a fetchnodes happens after a previous successful fetchnodes, the
init state of MEGAchat is `kInitHasOnlineSession`, which doesn't resume
actionpackets processing as it should --> in consequence, the app
doesn't get external changes and cannot complete a new fetchnodes.

Resume actionpacket processing after forced reload

---

src/chatClient.cpp
src/chatClient.h
src/chatdICrypto.h
src/megachatapi_impl.cpp
src/strongvelope/strongvelope.cpp
src/strongvelope/strongvelope.h

- Make decryption of chat-title wait for decryption of unified-key.
- Store unified-key encrypted in DB to avoid missing it upon
close/crash.
- Revamping of GroupChatRoom ctor.
- Code cleanup.

Make sure strongvelope initialize with unified-key

---

bindings/Objective-C/MEGAChatSdk.h
bindings/Objective-C/MEGAChatSdk.mm
bindings/java/nz/mega/sdk/MegaChatApiJava.java
src/base/retryHandler.h
src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h
src/karereCommon.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/presenced.cpp
src/presenced.h

This branch requires the app to call `MegaChatApi::retryPendingConnections(bool disconnect)` in order to properly retry connections.

Hotfix: improve reconnections

---

bindings/Objective-C/MEGAChatSdk.mm

An empty MEGAChatCall was initialized when the MegaChatCall was NULL.

 Return the MEGAChatCall or nil on 'chatCallForCallId' or 'chatCallForChatId' (Obj-C) 

---

bindings/Objective-C/MEGAChatSdk.mm

An empty MEGAChatCall was initialized when the MegaChatCall was NULL.

Return the MEGAChatCall or nil on 'chatCallForCallId' or 'chatCallForChatId' (Obj-C)

---

src/chatd.cpp

The sending queue is not properly updated when the sending item is modified, since the changes are not actually saved in the sending queue (but in cache).
On the other hand, the load of history when there are incoming messages still encrypted should follow as usual, instead of fail an assertion as it used to be.

Fixes to load history and sending queue

---

src/presenced.cpp

When the account is empty (no chats, no contacts), there's no users to
allow to see our presence status.

Fix wrong assert in presence::updatePeers()

---

src/megachatapi_impl.cpp

The member `lastGreenVisible` was missing :(

Fix copy-ctor for MegaChatPresenceConfig

---

src/megachatapi_impl.cpp

There was a bug in the intermediate layer: when the status was changed
to Online, it attempt to clear the "persist" option, but instead it used
to send the Busy and later the Online.

Fix Online presence keeping the "persist" option

---

src/karereCommon.h

One per geographical location, rather than most of the available ones.
Remember the ICE servers should be retrieved by GeLB, so they are load-
balanced instead of using the static ones by default.

Update static ICE servers

---

src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h

When the app tries to `loadMessages()` and it requires to fetch messages
from server but we're offline, it returns `SOURCE_ERROR` (`kSourceNotLoggedIn`). However, when
the connection is back and we are logged in into chatd, a new
`loadMessages()` should notify the received messages from server. It
loads them, but didn't notify them. The issue comes from the update of `mNextHistFetchIdx` at `onFetchHistDone()`, which doesn't take into account that there's no local history available at all.
Additionally, another bug was due to a (too) early assignment of `mServerOldHistCbEnabled` in
`getHistoryFromDbOrServer()`.
Additionally, this commit attempts to be more accurate with the
notification of `OLDMSG` after a `REJECT` of `JOINRANGEHIST` (if the
chat was not opened, we don't need to set the …

Fix load of messages after attempt while offline

---

src/base/promise.h
src/chatClient.cpp
src/megachatapi.h
src/presenced.h

Apps get a `onChatOnlineStatus(myHandle, status, inProgress)` when they
attempt to change the status to the same value than the currently
configured one (with `inProgress = true`). However, there's never
confirmation of the new status configuration success, since it's never
sent.

 Fail upon `setOnlineStatus()` with current value

---

tests/sdk_test/sdk_test.cpp

In order to avoid interferences with other existing sessions running at
the same time, we enforce no more sessions are valid at the time the
tests start

Close other sessions at Test's setup

---

bindings/Objective-C/MEGAChatSdk.h
bindings/Objective-C/MEGAChatSdk.mm
bindings/java/nz/mega/sdk/MegaChatApiJava.java
src/chatClient.cpp
src/chatClient.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h

iOS should also ensure it's up-to-date with chatd via SYNC. In case the
PUSH includes the chatid, the SYNC will be sent only for the specified
chatid.

Push received for iOS

---

src/megachatapi_impl.cpp

Added state kStateWaitLocalSdpAnswer in MegaChatSessionHandler::onSessStateChange(uint8_t newState) to fix initial state not being reported to iOS layer

Fix SESSION_STATUS_INITIAL not being reported

---

src/chatClient.cpp

Automated tests failed due to joins/logins into chatd in parellel for
the same chat. In result, the same message can be received as NEWMSG and
OLDMSG, which should never happen.

Skip rejoin if already joining

---

src/presenced.cpp

When the app checks if it should signal presence activity (to avoid
becoming automatically away), we had a bug if the client was in a call.

Fix presence autoaway

---

src/presenced.cpp

The higher state of the connection-state is `kLoggedIn`. If the socket
is closed at that state, the `assert(mRetryCtrl)` a few lines below (in
the `else` block) will systematically fail, since the RetryController is
deleted as soon as the connection reaches the state `kConnected`.

Fix presenced::onSocketClose()

---

examples/qtmegachatapi/MainWindow.cpp

- Remove chatlist cleanup upon onChatConnectionStateUpdate when we are
connected to all chats. If we clean the chat list the reorder will be
slower, and if any chat window is open it will be closed.

Fix QtApp reorder when we are connected to all chats

---

bindings/Objective-C/Karere.xcodeproj/project.pbxproj
bindings/Objective-C/MEGAChatContainsMeta.h
bindings/Objective-C/MEGAChatContainsMeta.mm
bindings/Objective-C/MEGAChatGeolocation.h
bindings/Objective-C/MEGAChatGeolocation.mm
bindings/Objective-C/MEGAChatSdk.h
bindings/Objective-C/MEGAChatSdk.mm
bindings/Objective-C/Private/MEGAChatGeolocation+init.h
bindings/java/nz/mega/sdk/MegaChatApiJava.java
examples/qtmegachatapi/chatMessage.cpp
examples/qtmegachatapi/chatMessage.h
examples/qtmegachatapi/chatWindow.cpp
examples/qtmegachatapi/chatWindow.h
examples/qtmegachatapi/chatWindow.ui
src/chatd.cpp
src/chatdMsg.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h

Geolocation is sent as contains meta sub type. The structure of the message is:
<0><kMsgContainsMeta><ContainstMetaSubType::kGeoLocation>{"textMessage":"www.maps.google.com/api=1?query:....","extra":[{"la":"...","lng":"...","img":"B64url encoded image"}]}
`textMessage` field at json will be mandatory for all contains meta subtype

Support for share-geolocation messages

---

src/megachatapi_impl.cpp

Messages from archived chats should not generate notifications.
However, inactive chats (where the user does not participate any more)
should be taken into account.

Skip notification for archived chats, add for inactive ones

---

src/chatd.cpp

Deleted messages may update the unread count, but only if the message is
edited by other than own user.

Fix update of unread-count upon deletion

---

src/megachatapi_impl.cpp

The number of contacts to be attached cannot be greater than the number of contacts.

Fix bug: it is not possible to attach contacts to a chat

---

examples/qtmegachatapi/MainWindow.cpp
src/chatClient.cpp
src/megachatapi_impl.cpp
src/presenced.cpp
src/presenced.h

- Avoid to update the list of peers for presenced from chatd JOINs.
- Avoid to send `SETPEERS` before catch-up phase (actionpackets received
after first `wsc`).
- Update peerlist (`ADDPEER`/`DELPEER`) only after catch-up phase.
- Register a `MegaGlobalListener` to receive changes in contact-list,
chats-peer-list and also the catch-up event.

Drive peerlist for presenced only from API

---

tests/sdk_test/sdk_test.cpp

API doesn't unarchive the chatroom upon new messages. Let's give it some extra time, as a temporal patch, and see if it improves the situation.

Temporal fix to avoid failures in tests related to Archive

---

src/rtcModule/webrtcAdapter.cpp

`webrtc/base` is deprecated https://bugs.chromium.org/p/webrtc/issues/detail?id=7634
Depending the webrtc version, using `base/ssladapter.h` would compile or not. The current webrtc version used in the iOS application doesn't have the `base/ssladapter.h` header file, so the compilation fails

Fix compilation error

---

src/buffer.h

The Undefined Behavior Sanitizer (UBSan) detects a Misaligned Pointer / Reference. 
A misaligned pointer has undefined behavior, and may result in a crash or degraded performance.
The problem is that `__arm__` is defined for 32bit arm, and 32bit arm only. At least. when using `clang`.
This pull request tries to solve this problem for arm64 devices.

Don't allow unaligned memory access for arm64 devices

---

src/rtcModule/webrtc.cpp

`mSessions.erase(sess.mSid)` was duplicated. We remove the session at the end of the function to avoid access an invalid reference `Session& sess`

Fix removeSession, remove session at the end of the function

---

bindings/java/nz/mega/sdk/MegaChatApiJava.java
examples/megaclc/megaclc.cpp
examples/qtmegachatapi/MainWindow.cpp
examples/qtmegachatapi/MainWindow.h
examples/qtmegachatapi/MegaChatApplication.cpp
examples/qtmegachatapi/MegaChatApplication.h
examples/qtmegachatapi/chatMessage.cpp
examples/qtmegachatapi/contactItemWidget.cpp
src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/presenced.cpp
src/presenced.h

When API path is changed to staging, not only a full fetchnodes is required, but also the URL for presenced is different, so it needs to be re-fetched and reconnected.

Support to refresh the chatd/presenced URLs and reconnect

---

src/rtcModule/webrtc.cpp

Abort session reconnection when we receive a user is offline. It's possible that webrtc detects a session fail before we receive a ENDCALL from chatd

Abort session reconnection when user is disconnected

---

src/chatClient.cpp
src/chatd.cpp
src/chatdMsg.h
tests/sdk_test/sdk_test.cpp
tests/sdk_test/sdk_test.h

We need to ensure that we are connected to chatd for all chats when we make login in every test. On the other hand if we create a new chatroom we need to ensure that we are connected to chatd before continue with the test.

Chatd connection improvements in automatic tests

---

src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h

The issue is: in a group with A, B and C
- A starts a call in the group chatroom
- B rejects the call
- C answers the call
Issue: B starts ringing again

Avoid ringing in again after reject a call

---

src/chatd.cpp
tests/sdk_test/sdk_test.cpp
tests/sdk_test/sdk_test.h

Upon `onJoinComplete()`, the `findLastTextMessage()` marshalls (1) the decission to fetch more old messages if no last-message is available, and that marshall call does a new marshall (2) to fetch messages (send `HIST`). At the same time, the app may attempt to load history, which marshalls (3) another fetch of old messages too (send `HIST`).
The resulting execution order is 1, 3, 2, and that results on the reset of the flag `mServerOldHistCbEnabled` for the `HISTDONE` corresponding to 3 --> the `onHistoryDone()` for 3 is not called, but expected by the app.

Fix race condition between findLastTextMessage and getHistory

---

tests/sdk_test/sdk_test.cpp

The timeout for autoaway is only checked at hearbeats, which happen every 10s. In consequence, the away could be set too late if the timeout is very low.
Since the apps do not allow to set it lower than 1 minute, the maximum delay of 10s is acceptable.

Adjust test for autoaway

---

src/presenced.h
tests/sdk_test/sdk_test.cpp

Also adjust autoaway's timeout to a lower one. The heartbeat's delay is acceptable, so better to reduce the elapsed time of the test.

Update presenced's documentation

---

tests/sdk_test/sdk_test.cpp

In the SetUp stage, MEGAchat's initialization is not needed at all. Better to avoid it, so accounts don't burn that fast :)

Avoid a full login during SetUp stage

---

src/base/logger.cpp

Add try-catch for `recursive_mutex::lock()` in order to capture the exception thrown by
the function. There are crash reports from iOS indicating that the static object `Logger` might be already destroyed when `logString()` is called. Apparently, iOS could be destroying the `Logger` object while the `MegaChatApi` instance is still running and logging messages. Hence, the exception upon trying to `lock()` an invalid instance of the mutex.
Due to the high frequency of calls to this function and the overhead introduced by the exception's handler, we will first check another workaround: iOS to force the destroy of the `MegaChatApi` upon app's termination. If the crash still reproduce, then we will merge this PR.

Prevent app crashes in logger

---

tests/sdk_test/sdk_test.cpp

A 1on1 still exists for ex-contacts, but they cannot operate in the room
unless they become contacts again.

Ensure both users are contacts

---

src/chatClient.cpp

In Anonymous mode there's no login/fetchnodes, so there's no need to wait for the completion of fetchnodes in order to proceed with the connection to chatd.
The assertion in `connect()` was failing due to the unresolved promise, so better to keep it resolved from the scratch, which simplify the code.

Do not wait for session ready in anonymous mode

---

tests/sdk_test/sdk_test.cpp

When we make login in anonymous mode we won't retrive user attributes
so we don't need to wait for it.

Fix wrong assert in public chats test

---

src/rtcModule/webrtc.cpp
src/rtcModule/webrtcPrivate.h

The dtor of the `Call` object, if called after the GC destroys the `WebRtcLogger` instance, will crash when accessing the logger. This PR aims to fix the segmentation fault.

Adjust deallocation of RtcModule resources

---

src/megachatapi_impl.cpp

When one attachment is loded in the node-history, but it's deleted afterwards, the deleted message is notified in `onAttachmentLoaded()` when it shouldn't. This commit aims to fix that behavior.

Skip notification about deleted attachments in node history

---

src/chatClient.cpp

It may happen that encryption of the unified key for all participants require to fetch some keys from API. In that case, where keys are not cached yet, the `encryptUnifiedKeyForAllParticipants()` requires API
requests and, in the meantime, the number of references to the shared pointer `crypto` becomes 0. In result, the encryption's promise fail (due to `throwIfDeleted()`), so does the creation of the chatroom.

Keep `ProtocolHandler` alive

---

src/chatd.cpp
src/chatdDb.h

This PR solve two issues:
- Avoid discontinuity at node history. Add a message to node history as soon as possible just before adding to history table at data base
- Added protection for potential issue with pending KeyCommand for already confirmed keys. Remove keyCommand from RAM and data base  when key is confirmed

Added protection for potential issue with pending KeyCommand for already confirmed keys

---

src/chatd.cpp

IOS and Android apps reported that they receive duplicated messages. The issue was that karere is notifying messages at first join and algorithm doesn't handle that case.

Avoid notify old messages to apps during login process

---

src/megachatapi_impl.cpp

In example, a tailing `/` or a potential `/<member_id>` in a future

Relax format restriction for chatlinks URLs

---

src/megachatapi_impl.cpp

It still requires the API to allow it. By now it returns `EACCESS`

Allow to retrieve existing chatlinks for non-moderators

---

bindings/Objective-C/MEGAChatSdk.mm
bindings/java/nz/mega/sdk/MegaChatApiJava.java
examples/megaclc/megaclc.cpp
examples/qtmegachatapi/MainWindow.cpp
examples/qtmegachatapi/MegaChatApplication.cpp
examples/qtmegachatapi/MegaChatApplication.h
examples/qtmegachatapi/chatItemWidget.cpp
examples/qtmegachatapi/chatMessage.cpp
examples/qtmegachatapi/contactItemWidget.cpp
src/chatClient.cpp
src/chatClient.h
src/chatd.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/strongvelope/strongvelope.cpp
src/strongvelope/strongvelope.h
src/userAttrCache.cpp
src/userAttrCache.h
tests/sdk_test/sdk_test.cpp

In preview mode the unified key is used to encrypt messages, so the public Cu25519 key of senders is not needed, only the public Ed25519 to verify the signature.
(firstname/lastname will be requested at Member's ctor and, for ex-participants, app will request them on demand through MegaChatApi::getUserFirstname/Lastname(userid, ph))

Fix retrieval of usernames in preview mode

---

src/megachatapi_impl.cpp

In MegaChatApiImpl ctor the request tag was not initialized so request
tag could contain a random number.

Fix Init MEGAchat request tag

---

examples/qtmegachatapi/MainWindow.cpp
examples/qtmegachatapi/MainWindow.h
src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h
src/megachatapi.h
src/megachatapi_impl.cpp
src/net/libwebsocketsIO.cpp
src/net/websocketsIO.cpp
src/net/websocketsIO.h
src/presenced.h

If the init was not called yet or if MEGAchat is not connected to all shards, the `MegaChatApi::setBackgroundStatus(true)` will return `ERROR_ACCESS`.
Also, the request will fail if no socket is available to send data.

Report failure upon set background status

---

src/chatClient.cpp
src/chatClient.h

At `stageEnd(kStatsPostFetchNodes)` the assertion fails, since in anonymous mode the stage was not never started, @jgandres. That stage should finish at the right time, in the `onRequestFinish()` of fetchnodes.

Adjust init stats in anonymous mode

---

src/chatd.cpp
src/chatd.h

If there is a buf queued for sending, but before sending the client is destroyed, the app may crash. This commit prevents the issue.

Check status of object for `mSendPromise` handlers

---

src/chatd.cpp

Due to a race-condition at client-side receiving the removal of own user from API and chatd, if own user was the only moderator, chatd sends the JOIN 3 for remaining peers followed by the JOIN -1 for own user. However, API response might have already cleared the peer list. In that case, chatd's removal needs to clear the peer list again, since remaining peers would have been added as moderators.

Clear peerlist from chatd's JOIN -1

---

src/chatClient.cpp

In case no firstname is available but lastname exists we need to check
buffer size because the size of firstname (0) is written in first the byte.

Adjust peer chatrooms title when no firstname is available

---

src/chatClient.cpp
src/chatClient.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h

When the app is running and another instance is launched i.e (share-extension in iOS),
chatd drops the connection if detects that the clientid already exists.

Feature #11983: Reset clientid

---

bindings/java/nz/mega/sdk/MegaChatApiJava.java

Remove the `enableGroupChatCalls(bool)` and `areGroupChatCallEnabled()` methods from Android bindings.

Groupcalls always enabled (Android bindings)

---

src/chatd.cpp

If `MegaApi::setBackgroundStatus()` is called right before a `MegaApi::~MegaApi()`, it may result in a crash due to the `.fail()` associated. This commit aims to avoid propagation of the rejected promiste to the intermediate layer.

Add .fail handler for keepalive upon exit

---

src/megachatapi.h
src/megachatapi_impl.cpp

In mobile apps the "Connecting" label is removed too early, when the
call isn't fully operative so we need to notify apps when the call
is usable.

Bug #11953 create new change type to notify apps when a call is fully operative

---

src/megachatapi_impl.cpp

The `i` and/or `ic` fields in the json returned by api could have an
invalid B64 format. In order to fix it we check the expected length
after convert it to binary, and check that the difference with the
returned value of atob is under 2 (considering the padding ==)

Bug #12183 Protect against invalid JSON for rich-links

---

examples/qtmegachatapi/MainWindow.cpp
examples/qtmegachatapi/SettingWindow.cpp
examples/qtmegachatapi/SettingWindow.h
examples/qtmegachatapi/SettingWindow.ui
src/chatClient.cpp
src/chatClient.h
src/chatd.cpp
src/chatd.h
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/presenced.cpp
src/presenced.h

- Hide non-contacts presence status.
- Avoid to send `USERACTIVE 1` if connected in background.
- Add presence config to SettingsWindow in QtApp.

Hide presence status for non-contacts

---

src/chatClient.cpp
src/chatClient.h

In order to discard samples with atypical values because of inactivity periods, we need to cancel statistics when the app tries to connect in background or when the apps goes to background.

Cancel statistics when apps goes to background

---

src/chatd.cpp

Some services as facebook introduce a special string in mega urls. Detect this special cases and avoid to manage as rich link

#12877 Not manage as rich link mega urls

---

examples/qtmegachatapi/MainWindow.cpp
examples/qtmegachatapi/MegaChatApplication.cpp
examples/qtmegachatapi/MegaChatApplication.h
examples/qtmegachatapi/contactItemWidget.cpp
examples/qtmegachatapi/contactItemWidget.h
src/chatClient.cpp
src/chatClient.h
src/userAttrCache.cpp
src/userAttrCache.h

Wherever a firstname / fullname is currently displayed, if the user has assigned to him/her a nickname, it should prevail. In example, default groupchat title, notifications about new messages, sender of a message, etc.

#12551 Use nickname if available

---

src/presenced.cpp

The user received in the `onUsersUpdate()` is still an unknown user for presenced's client. However, it's added to the list of users not as contact, but directly as ex-contact. In that case, the visibility is
HIDDEN and it should not be added to the list of current peers managed by presenced.

#13077. An unknown user can be notified directly as ex-contact

---

src/chatdMsg.h
src/strongvelope/strongvelope.cpp

For public chats keyid is 0 for all messages, so we can't check keyid
to identify if a message is a management message or not.
To solve this problem now we will check if the userid is the API user,
except for truncate messages and if message type is a management known
type.

#13115. Fix isManagementMessage

---

src/rtcModule/webrtc.cpp
src/rtcModule/webrtcPrivate.h

If two clients answer an incoming call roughly at same time, a session is established between the 2 clients of the same user (apart from the sessions between the 2 clients and the caller). I could result on the wrong streams being received by the other peer. In example, User A sees video from user B (client 1: B1), but user B in client 2 (B2) sees the video from B1.
**Risk area/s:**
- 1on1 calls answered at two clients at the same time (only one client should success answering the call).
- Group calls answered at two clients of the same user, which is allowed.

#13141. Avoid conflict in 1to1 calls when two clients answer at same time

---

src/rtcModule/webrtc.cpp

This is a special case in group call where caller drop internet but several partipants answer the call. This call has to continue because it has been established correctly
Risk area/s:
- Group call where caller drop internet before none answer, immediately several participants answer the call

#13187. Avoid finish call with kErrSessSetupTimeout if caller drop internet

---

contrib/QtCreator/MEGAChatQt/MEGAChatQt.pro

The SDK doesn't need libraw to work, but it improves UX because it generates previews of RAW format images. Altough is not specified in configure, HAVE_LIBRAW is added to config.h as long as libraw is available in the system.
We need to add libraw as QtApp dependency.
**Risk area/s:**
- QtApp construction

#13283. Fix QtApp construction by adding libraw as dependency

---

src/chatd.cpp
src/presenced.cpp

Some DNS servers reply with IPv6 only addresses when promted from IPv6-only networks. It results on cached IPs only for v6. After switch to a IPv4-only network, the connection attempt to IPv6 fails immediately and the IPv4 is empty, so it results on a new retry. When the DNS resolution arrives, it detects the received IPs corresponds to a previous attempt, so it discards them.
All the above results in a non-recoverable situation where only networks with IPv6 connectivity will successfully connect.
Risk area/s: 
- Switch between networks with different IP families: IPv4 <--> IPv6

#13690. Wait for DNS resolution if missing cached IP family

---

examples/qtmegachatapi/chatWindow.cpp

In case of media files, this method ensures that the thumbnail/preview are created in case they are missing in a existing node for the same file.

Use uploads for chat

---

src/chatClient.cpp

**Risk area/s**
- Remove a participant from a chat and re-invite. After rejoin, new history (which user is entitled to see) must be received successfully.

#13891. Avoid Send a new JOIN to chatd upon re-join

---

examples/megaclc/megaclc.cpp

- this ensures we reload email/names if the chat room doesn't provide them
- also moved the one-shot-listeners further up

Improve loading of email/names for reviewpublicchat

---

bindings/java/nz/mega/sdk/DelegateMegaChatRoomListener.java
bindings/java/nz/mega/sdk/MegaChatApiJava.java

Callbacks from MegaChatRoomListener are queued by DelegateChatRoomListener in order to be executed by the app's thread. In result, the execution may happen when the chatroom has been closed.
Since the MegaChatRoomListenerInterface is reused by the app for a new DelegateChatRoomListener when another chatroom is opened, it may receive outdated callbacks, corresponding to the already closed chatroom.
This commit aims to avoid such race condition by properly invalidating the listener when the chatroom is closed.

#14071. Avoid race conditions on DelegateChatRoomListener

---

src/sdkApi.h

The instance could have been deleted by the time the `onRequestFinish()` is called. Without this protection (already available at `MyListener::onRequestFinish()`), the marshall call will access to the
`EventQueue` that has already been destroyed.

#14151. Avoid callback if deleted

---

src/chatd.cpp

When an edited message is edited again, but being offline, upon reconnection chatd sends the previous edit, which used to discard the pending (newer) edit. That edition should be resent if it is newer than
the received edition.
Additionally, if a message is truncated, any further edit is futile, so the item can be discarded from the pending queue as well.

#14205. Keep pending edits upon reconnect

---

src/rtcModule/OBJCCaptureModule.mm
src/rtcModule/webrtc.cpp
src/rtcModule/webrtcAdapter.cpp
src/rtcModule/webrtcAdapter.h
src/rtcModule/webrtcPrivate.h

We have change the way of manage a VideoManager object. Now, we use a rtc::scoped_refptr. 
During tests, we detect that changing  the video source during a call produce a memory invalid access.
Although, we have to define a rtc::scoped_refptr in webrtcPrivate.h this solution is less complicated than keep the shared_ptr

Use rtc::scoped_refptr to manage VideoManager

---

examples/megaclc/megaclc.cpp

- It was requested for `rpc` to output info for all message types
- Changed message output to be generic

rpc command: add output of more messages types

---

src/rtcModule/webrtc.cpp

Android team has detected an issue with mobile `MI 9T`. The camera doesn't close after a call

#14448. Release video device when call is finished

---

src/rtcModule/webrtc.cpp

The variable mManager has invalid value when Call object is destroyed. We keep mManager pointer to use in the timer

#14598. HotFix: Fix invalid access to variable after destroy the object

---

src/chatd.cpp
src/net/libwebsocketsIO.cpp
src/net/libwebsocketsIO.h
src/net/websocketsIO.cpp
src/net/websocketsIO.h
src/presenced.cpp

Avoid concurrent access to the DB due to callbacks from libwebsockets skipping the `sdkMutex.lock()`

#14601. HotFix: Marshall the callback from libwebsockets for DNS resolution

---

src/rtcModule/webrtc.cpp

The variable mManager has invalid value when Call object is destroyed. We keep mManager pointer to use in the timer

#14598. Fix invalid access to variable after destroy the object

---

src/rtcModule/webrtc.cpp

In some situations, IOS app is forcing a network reconnection after answer a call. In normal condition, call reconnection is successful but when we have some network issue, the reconnection finishes with failure (after time-out) and call is finished unsuccessfully
This PR solve the issue and call reconnection will be successful if app recovers the network correctly

#14656.  Call gets in reconnected state after answer

---

src/chatClient.cpp

When the account get blocked, depending on the reason, the SDK may automatically logout (without closing the session). In that case, MEGAchat should also logout.
NOTE: wait for https://github.com/meganz/sdk/pull/1919 to be merged first

#14917. Add auto-logout when SDK logs out due to EBLOCKED

---

bindings/Objective-C/MEGAChatCall.h
bindings/Objective-C/MEGAChatCall.mm
bindings/Objective-C/MEGAChatCallDelegate.h
bindings/Objective-C/MEGAChatSession.h
bindings/Objective-C/MEGAChatSession.mm
bindings/Objective-C/Private/DelegateMEGAChatCallListener.h
bindings/Objective-C/Private/DelegateMEGAChatCallListener.mm
bindings/java/nz/mega/sdk/DelegateMegaChatCallListener.java
bindings/java/nz/mega/sdk/MegaChatCallListenerInterface.java
bindings/qt/QTMegaChatCallListener.cpp
bindings/qt/QTMegaChatCallListener.h
bindings/qt/QTMegaChatEvent.cpp
bindings/qt/QTMegaChatEvent.h
examples/qtmegachatapi/MainWindow.cpp
examples/qtmegachatapi/MainWindow.h
src/megachatapi.cpp
src/megachatapi.h
src/megachatapi_impl.cpp
src/megachatapi_impl.h
src/rtcModule/webrtc.cpp
src/rtcModule/webrtc.h
src/rtcModule/webrtcPrivate.h

Do not merge this PR until Android and iOS are ready to merge the corresponding integrations.
- Create new callback at MegaChatApi level onChatSessionUpdate
- Notify all session changes with this new callback
- Detail peerid and clientid at notification CHANGE_TYPE_CALL_COMPOSITION
- Update QT app

#13262. Refactor session notifications

---

src/chatClient.cpp
src/megachatapi.h

Checking every message that may have been edited via a new SQLite statement becomes a bottleneck with a relevant amount of chats. Better to check only those msgs that have been edited, and check if edit is newer.

#15019. Improve performance for edits

---

bindings/Objective-C/MEGAChatSdk.h
bindings/Objective-C/MEGAChatSdk.mm
src/rtcModule/OBJCCaptureModule.mm

- Don't force the front camera in `OBJCCaptureModule` class.
- Removed unused method declarations.
Should be merged along with https://github.com/meganz/iOS_dev/pull/555

Updated Objective-C bindings

---

src/megachatapi_impl.cpp

#15638. Add missing ERROR_TOOMANY in MegaChatErrorPrivate::getGenericErrorString

---

src/chatClient.cpp

It may happen the App knows about a chatid that is unknown by the NSE. In that case, upon import, the SEEN statement will not return any data.

#15563. Hotfix for SEEN import

---

examples/qtmegachatapi/chatMessage.cpp
src/chatClient.cpp
src/megachatapi_impl.cpp

When a new message is received, but it is already SEEN, the `onChatNotification()` should not be called in case the message is still being decrypted. Once decrypted, a callback, if suitable, will be
triggered.

#15729.  Avoid to notify about messages being decrypted

---

src/chatd.cpp

Now that SEEN pointer can be imported from the NSE, it might be outdated compared with the SEEN pointer in the app. In that case, we need to skip any update of the SEEN pointer, of the count of unread messages, etc.

#15770. Avoid to set SEEN back in history

---

src/chatd.cpp

Now that SEEN pointer can be imported from the NSE, it might be outdated compared with the SEEN pointer in the app. In that case, we need to skip any update of the SEEN pointer, of the count of unread messages, etc.

#15770. Avoid to set SEEN back in history (hotfix for develop)

---

examples/qtmegachatapi/MegaChatApplication.cpp

As per requested by MEGA, any app connecting to the API should provide a valid `appKey`
> https://mega.nz/sdk

Use a valid app key for QtApp

---

src/chatClient.cpp

In case of canceled accounts, the peerchat remains, but not the ex-contact. If the account is restored and the user becomes a contact again, it's needed to attach the orphan 1on1 room to the contact.

#15994. Cannot create chat upon canceled contact restore

---

bindings/java/nz/mega/sdk/MegaChatApiJava.java

This method uses string resources of the official MEGA app, so this code has been moved to the app code (https://github.com/meganz/android2/pull/1291/commits/13b0f7fab9940d309eb38d044c58ed5658dce2df)

Remove `getTranslatedErrorString` method from Android bindings

---

src/presenced.cpp

Now that the SDK includes an assert to not retrieve the `scsn` earlier than initialized, MEGAchat fails that assertion by getting it too early. There was no bug, since the `mLastScsn` is invalid until the SDK notifies, via `onEvent(EVENT_NODES_CURRENT)`, that the `scsn` has been initialized.

Adjust checks at presenced onUsersUpdate

---

src/chatd.h

DO NOT merge this PR until chatd v8 has been deployed to all shards (currently only in shard2).

#16499. Upgrade chatd version to 8

---

src/userAttrCache.cpp

Composed attrs are synthesized by other attributes, so if any of these
attributes change, we would need to re-fetch the composed attr to avoid
have it outdated.

#16569. MegaChatApi::getMyFullname() return wrong fullname

---

src/strongvelope/strongvelope.cpp

The `keyid` has been recently changed from `uint64_t` to `uint32_t`. It does not cause any issue on 64bits binaries, but on certain libc stacks on Android phones, it may crash at `strlen()`

CHT-414. Adjust datatype for log message

---

src/chatd.cpp
src/chatdDb.h

When messages are imported, they can pass twice through `msgIncomingAfterDecrypt()`, which results on increasing the unread
count more than once for the same message. Better to recalculate.

CHT-417. Fix wrong update of unread messages

---

src/chatd.cpp
src/chatdDb.h

When messages are imported, they can pass twice through `msgIncomingAfterDecrypt()`, which results on increasing the unread
count more than once for the same message. Better to recalculate.

CHT-417. Fix wrong update of unread messages (HOTFIX for develop)

---

src/megachatapi_impl.cpp

The break refers to the loop `for`, not to the switch

CHT-423. Fix wrong error management

---

src/strongvelope/strongvelope.cpp

Upon encrypt/decrypt a reaction of a message, the key to encrypt the reaction depends on the key used to encrypt the message. Hence, when reacting to a message posted in EKR off, but the chat is EKR on, the key should be the unified key, not the specific key of the message (which does not exist).

CHT-433. Select right key for reaction in private mode
