meganz/MEGAchat

src/megachatapi_impl.cpp
MEGAsync relies on the fingerprint for synchronization, so it's better
to include that information.
=> Add fingerprint to JSON of attachments

bindings/java/nz/mega/sdk/MegaChatApiJava.java
Updated deprecated methods and added the new ones to attach and revoke nodes
=> Update Android bindings

tests/sdk_test/sdk_test.cpp
This changes have been added at branch feature/inactive-contacts-chats too
=> Solve errors at group chat Tests

src/chatClient.cpp, src/chatClient.h, src/presenced.cpp, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, src/rtcModule/webrtcPrivate.h
Avoid user becomes inactive while a call is in progress
=> Send signalActivity when call is in progress

src/megachatapi.cpp, src/megachatapi.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, tests/sdk_test/sdk_test.cpp
Add field to MegaChatCall to notify to apps the reason by the call has finished
=> Notify termination code from intermediate layer to apps

src/megachatapi_impl.cpp, src/rtcModule/webrtc.cpp, tests/sdk_test/sdk_test.cpp
Check if start chatcall request has finished correctly
=> Check if rtc module is initialized correctly before it is used

examples/qt/chatWindow.cpp, examples/qt/chatWindow.h, src/chatd.cpp, src/chatd.h, src/chatdDb.h, src/chatdMsg.h, src/megachatapi.cpp, src/megachatapi.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h
=> Implement reject JOINRANGEHIST when un-received history is much long

bindings/Objective-C/Karere.xcodeproj/project.pbxproj, src/IGui.h, src/chatClient.cpp, src/megachatapi_impl.h
In Xcode project:
- Remove references to webrtc code
- Remove duplicated cflags - Remove paths to libws, libevent and webrtc
=> Fix compilation issue with macro KARERE_DISABLE_WEBRTC

src/chatd.cpp
Furthermore, local last seen is sent to server in this situation
=> Keep local last seen if server last seen is older

src/megachatapi_impl.cpp, src/megachatapi_impl.h
Add mutex to control access to remoteVideoListeners and localVideoListeners
=> Hotfix for v1.1.0

src/megachatapi_impl.cpp, src/presenced.cpp, src/presenced.h
This data is used by clients to know if the user has any client capable to receive calls.
=> Send WebRTC capability to presenced

bindings/megachatapi.i
and recent versions of the SDK
=> Compatibility with SWIG 3.0.12

src/chatd.cpp, src/net/libwebsocketsIO.cpp, src/rtcModule/webrtc.cpp
- Fix log message
- Add reason for closing socket
- Update doc
=> Minor fixes

bindings/qt/megachat.pri
Add all the missing header files to the project structure
=> Include header files in .pro

src/rtcModule/rtcStats.cpp, src/rtcModule/rtcStats.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtcPrivate.h, tests/sdk_test/sdk_test.h
UserAgent is similar to:
- MEGAAndroid/3.3_179 (Linux 3.10.49-g765430a armv7l) MegaClient/3.3.0
- MEGAChatTest (fedora 27/Linux 4.14.14-300.fc27.x86_64 x86_64) MegaClient/3.3.0 
- MEGAsync/3.6.0.0
- MEGAiOS/3.8.2 (...)
=> Add device information at the json from stats

examples/qt/main.cpp, src/IGui.h, src/chatClient.cpp, src/chatd.cpp, src/chatd.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/net/libwebsocketsIO.cpp, src/net/libwebsocketsIO.h, src/net/libwsIO.cpp, src/net/libwsIO.h, src/net/websocketsIO.cpp, src/net/websocketsIO.h, src/presenced.cpp, src/presenced.h, src/sdkApi.h
To be applied to `develop` if no critical issues are found in the coming days.
=> Hotfix: use libuv for DNS

src/megachatapi_impl.cpp
... to help apps to check if there are other chatrooms with same participants upon new chat's creation, so they can offer the user to reuse an existing chat.
=> Get chat-list-items by peer

src/strongvelope/strongvelope.cpp
In order to avoid spoofed messages that may attempt to use the keyid or
userid for management messages, this commit will ignore them and log a
warning message.
=> Ignore management messages with invalid userid or keyid

src/megachatapi_impl.cpp, tests/sdk_test/sdk_test.cpp
At TestChatRoomListener::onMessageUpdate check `change type` before update any state variable
=>  Fix issue at attachment test

examples/qtmegachatapi/chatMessage.cpp, examples/qtmegachatapi/chatWindow.cpp, src/chatd.cpp, src/chatd.h, src/chatdDb.h, src/chatdICrypto.h, src/chatdMsg.h, src/karereId.h, src/megachatapi.h, src/megachatapi_impl.cpp, src/strongvelope/strongvelope.cpp
Different errors at decryption stage should be treated differently by the apps
=> Manage errors at strongvelope

bindings/Objective-C/MEGAChatSdk.h, bindings/Objective-C/MEGAChatSdk.mm
- Added removeRichLinkForChat:messageId: method
=> Updated Objective-C bindings

src/megachatapi_impl.cpp, src/rtcModule/webrtcAdapter.cpp, src/serverListProvider.h
For this branch is necessary SDK branch 'fingerprint-conversion' (PR: https://github.com/meganz/sdk/pull/1117)
=> Transform from SDK fingerprint to MEGA figerprint

src/rtcModule/webrtc.cpp, tests/sdk_test/sdk_test.cpp
Furthermore this branch fix test with correct termination code
=>  Fix an issue with call cancel termination code 

src/chatd.cpp, src/chatd.h, src/chatdMsg.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, src/rtcModule/webrtcPrivate.h
- Implement CALLTIME command
- Improve calculation for call duration
=> Implement CALLTIME command and calculate call duration

bindings/Objective-C/MEGAChatCall.h, bindings/Objective-C/MEGAChatSession.h, bindings/Objective-C/MEGAChatSession.mm, examples/qtmegachatapi/callGui.cpp, src/megachatapi.cpp, src/megachatapi.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/rtcModule/IRtcStats.h, src/rtcModule/rtcStats.cpp, src/rtcModule/rtcStats.h, src/rtcModule/streamPlayer.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, src/rtcModule/webrtcPrivate.h
- Adapt webrtc stats to last webClient changes
- Calculate session network quality
- Calculate peer audio level
Pending for bindings before merging!
=> Calculate session network quality and audio level

examples/qtmegachatapi/MegaChatApplication.cpp, src/chatd.cpp
Management messages don't have content, but now are suitable for last-
msg
=> Fix assert

src/megachatapi_impl.cpp, src/megachatapi_impl.h
Add missing class attributes at copy constructor
Remove unnecessary code
=> Fix bug at MegaChatCallPrivate constructor

src/rtcModule/IRtcStats.h, src/rtcModule/rtcStats.cpp, src/rtcModule/rtcStats.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, tests/sdk_test/sdk_test.cpp, tests/sdk_test/sdk_test.h
Modify webRtc stats
Improve performance to calculate if we should add a new sample
=> Modify webRtc stats

src/chatClient.cpp, src/chatd.cpp, src/chatd.h, src/chatdDb.h, src/chatdMsg.h, src/dbSchema.sql, src/karereCommon.cpp, src/megachatapi.h, src/megachatapi_impl.cpp, src/strongvelope/strongvelope.cpp
This branch can't be merged until the command OP_NEWNODEMSG will be managed in all shards
=> Signal node-attachment messages to chatd

Readme.md, bindings/qt/megachat.pri
- Update readme Md content about new QTapp and the way to construct
MEGAchat.
- Adjust path in .pri file
=> Adjust build script to compile QTapp

src/chatd.cpp
- Check `isValidLastMessage` to prevent submit an invalid message type.
=> Feature check msg validity before submit

src/chatClient.cpp, src/chatClient.h, src/megachatapi_impl.cpp
Wait for merge https://github.com/meganz/sdk/pull/1255 first.
=> Add creation ts for previews

src/base/retryHandler.h, src/chatd.cpp, src/presenced.cpp
Async DNS lookups do not have any timeout in libuv. In consequence,
several lookups may get queued in result to several reconnection
attempts, breaking the RetryController's logic.
In order to avoid so, a DNS-lookup will be ignored if already connected
to cache IP, if there's a newer RetryController in place (due to a
forced disconnect) or if the DNS-lookup corresponds to a
previous/outdated attempt.
=> Ignore DNS-lookups if outdated

contrib/QtCreator/MEGAChatQt/MEGAChatQt.pro, examples/qtmegachatapi/MainWindow.cpp, examples/qtmegachatapi/MainWindow.h, examples/qtmegachatapi/MainWindow.ui, examples/qtmegachatapi/MegaChatApplication.cpp, examples/qtmegachatapi/MegaChatApplication.h, examples/qtmegachatapi/chatGroupDialog.cpp, examples/qtmegachatapi/chatItemWidget.cpp, examples/qtmegachatapi/chatItemWidget.h, examples/qtmegachatapi/chatMessage.cpp, examples/qtmegachatapi/chatMessage.h, examples/qtmegachatapi/chatWindow.cpp, examples/qtmegachatapi/chatWindow.h, examples/qtmegachatapi/contactItemWidget.cpp, examples/qtmegachatapi/contactItemWidget.h, examples/qtmegachatapi/listItemController.cpp, examples/qtmegachatapi/listItemController.h
The new dessign for listItems in QtApp pretends to implement an MVC pattern.
=> Improve listItems dessign in QtApp

src/megachatapi_impl.cpp, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, src/rtcModule/webrtcPrivate.h
- Add ringing flag at CALLDATA protocol
- Remove RTCMD_CALL_TERMINATE usage
- Other minor changes
=> Add new changes to group call branch

bindings/Objective-C/MEGAChatListItem.mm, bindings/Objective-C/MEGAChatMessage.h, bindings/Objective-C/MEGAChatMessage.mm, bindings/Objective-C/MEGAChatSdk.h, bindings/Objective-C/MEGAChatSdk.mm, bindings/java/nz/mega/sdk/MegaChatApiJava.java, examples/qtmegachatapi/MegaChatApplication.cpp, examples/qtmegachatapi/chatItemWidget.cpp, examples/qtmegachatapi/chatMessage.cpp, examples/qtmegachatapi/chatMessage.h, examples/qtmegachatapi/chatWindow.cpp, examples/qtmegachatapi/chatWindow.h, src/chatdDb.h, src/chatdMsg.h, src/megachatapi.cpp, src/megachatapi.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h
Add new message type kMsgVoiceClip and add support in MEGAChat to
manage new type of message.
=> Support for voice clips

src/chatClient.cpp, src/megachatapi.h, src/megachatapi_impl.cpp
The documentation to the following functions has been modified:
- openChatPreview
- setPublicChatToPrivate
- autojoinPublicChat
- autoRejoinPublicChat
- removeChatLink
- createChatLink
- checkChatLink
=> Adjust chatlinks errcodes

src/megachatapi.h, src/megachatapi_impl.cpp
The documentation to the following functions has been modified:
- attachNode
- inviteToChat
- updateChatPermissions
- archiveChat
=> Adjust new errcodes and documentation.

src/chatClient.cpp
Avoid access to unique pointers without value
=> Fix issue at terminate when client has never connected

requirements.sh
=> adding requirements installation file

src/IGui.h, src/chatClient.cpp, src/chatClient.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h
Both login and contacts management is always done through MEGA SDK
=> Cleanup `IApp` from login and contact interfaces

src/chatClient.cpp, src/chatClient.h, src/chatd.cpp, src/chatd.h, src/megachatapi_impl.cpp, src/presenced.cpp, src/presenced.h
- Create a Map of userids (key) and last green (value)
- Update last seen with last message ts if it's more recent
- Avoid update last seen with last message ts if we have requested last
seen to server and we don't have received any response
=> Consider timestamp of lastest message as last seen

examples/megaclc/megaclc.cpp, src/base/cservices.cpp, src/presenced.cpp
Also addressed gettimeofday() usage under MSVC
=> Added command apiurl to megaclc

bindings/Objective-C/MEGAChatSdk.h, bindings/Objective-C/MEGAChatSdk.mm
Bindings for getMaxVideoCallParticipants and getMaxCallParticipants methods
=> Objective-C bindings

src/rtcModule/rtcStats.cpp, src/rtcModule/webrtc.cpp
https://github.com/meganz/MEGAchat/pull/581 doesn't solve the issue
=>  Solve issue at Call::removeSession. Call terminating has to remove the session

src/megachatapi_impl.cpp
This PR is for the changes in https://github.com/meganz/sdk/pull/1357. Wait for its merge before proceed
=> Adjust params for MegaNodePrivate ctor

examples/qtmegachatapi/MegaChatApplication.cpp, src/base/logger.cpp, src/base/logger.h, src/karereCommon.cpp, src/karereCommon.h, src/rtcModule/rtcmPrivate.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h, src/rtcModule/webrtcPrivate.h
This PR has to be closed just after merging this one https://github.com/meganz/sdk/pull/1367
=> Send webRtc errors to karere stats server

src/megachatapi_impl.cpp, src/rtcModule/webrtc.cpp
Missing reasons for call termination.
Unify clientid printout to be all hexadecimal.
=> Improve log messages

src/rtcCrypto.cpp, src/strongvelope/strongvelope.cpp
This branch adjust the code for changes in SDK, https://github.com/meganz/sdk/pull/1376
=> Non static PrnGen object

src/chatd.cpp, src/chatd.h, src/chatdDb.h
Fix some issues at node history
=> Update mOldestIdx with data base index 

src/base/asyncTools.h, src/base/logger.cpp, src/base/retryHandler.h, src/chatClient.cpp, src/chatd.cpp, src/karereCommon.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtcAdapter.h, src/serverListProvider.h, src/strongvelope/strongvelope.cpp
In order to avoid posible ambiguous references we have added the scope
resolution operator to promise references.
=> Fix ambiguous promise reference

examples/megaclc/megaclc.cpp, src/chatClient.cpp
=> Revert "megaclc: add recentactions command"

examples/megaclc/megaclc.cpp
added a command to exercise getSpecificAccountDetails
=> megaclc: command to getspecificaccountdetails

examples/megaclc/megaclc.cpp
=> Revert "megaclc: command to getspecificaccountdetails"

src/chatClient.cpp, src/chatd.cpp, src/chatd.h, src/chatdDb.h, src/karereCommon.cpp
Set correctly mLastMsgTs for truncate messages
=>  Update keyid for truncate messages

bindings/Objective-C/MEGAChatContainsMeta.mm, src/megachatapi_impl.cpp
=> Delete the mGeolocation object in MegaChatContainsMetaPrivate dtor

contrib/cmake/CMakeLists.txt, src/chatClient.h, src/chatd.cpp, src/chatdDb.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/net/libwebsocketsIO.cpp, src/net/libwebsocketsIO.h, src/net/websocketsIO.cpp, src/net/websocketsIO.h, src/serverListProvider.h
Also addressed the most verbose of the template warnings.
=> Update for SDK moving to std::mutex

src/chatClient.cpp
In case the client is not logged in into chatd upon PUSH reception, and when the CATCHUP with API happens faster than login into chatd, MEGAchat may fail to notify new messages.
=> #12479. Fix push-received

examples/megaclc/megaclc.cpp
also a test function for exercising pushReceived
(needs SDK branch merged first)
=> WIP: megaclc: added getcloudstorageused for testing  (needs SDK branch merged first)

src/chatd.cpp, tests/sdk_test/sdk_test.cpp, tests/sdk_test/sdk_test.h
Furthermore add new format for mega links, we have added a unitary test for method chatd::Message::hasUrl()
=> #13085. Manage new mega links format

src/chatClient.cpp, src/megachatapi_impl.cpp
Risk area/s:
- Create new chatroom
=>  #13274. Avoid to create a chat if already exists

src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtc.h
**Risk area/s:**
- During a call change connection between wifi to 3G or between several wifis
=> #13128. Avoid notify terminating user participanting at reconnection state

examples/megaclc/megaclc.cpp
Needs the branch of the same name in the SDK
=> megaclc: Add -order parameter for exec_ls

examples/megaclc/megaclc.cpp
needs the SDK branch of the same name.
=> #13644 megaclc: added test commands for get/setcamerauploadfoldersecondary.

src/chatd.cpp, src/chatd.h
**Risk area/s:**
- Load history from server
=> #13733. Fix history reload upon JOINRANGEHIST REJECT

examples/megaclc/megaclc.cpp
- works around history loading problems
- adds debug output
- removes bogus joined/left function
- fixes spelling
=> Workaround for history loading problems

examples/megaclc/megaclc.cpp
- Ensure we write output file to the exe's path for reviewpublicchat (needed when user double-clicks on exe)
- Ensure we flush every line to the file immediately
=> reviewpublicchat file output

src/rtcModule/webrtcAdapter.h
=> #14422. Use OnFauilure(RTCError error)  in SetSessionDescriptionObserver::OnFailure

examples/qtmegachatapi/MainWindow.cpp, examples/qtmegachatapi/MegaChatApplication.cpp, src/chatClient.cpp, src/chatClient.h, src/megachatapi_impl.cpp, src/userAttrCache.h
Karere client needs to manage the transition from ex-contact to contact in order to update certain critical attributes (first/lastname). The code has heavily been simplified for better readability.
=> #13760. User attributes outdated for Non-Contacts and Ex-contacts

bindings/Objective-C/MEGAChatCall.h
To allow to get all calls regardless their state using chatCallsWithState
=> Add Undefined to call status enumeration

bindings/Objective-C/MEGAChatRequest.h, bindings/Objective-C/MEGAChatSdk.h, bindings/Objective-C/MEGAChatSdk.mm, bindings/java/nz/mega/sdk/MegaChatApiJava.java, examples/qtmegachatapi/MainWindow.cpp, examples/qtmegachatapi/MainWindow.h, examples/qtmegachatapi/chatWindow.cpp, src/chatClient.cpp, src/chatClient.h, src/chatd.cpp, src/chatd.h, src/chatdICrypto.h, src/db.h, src/megachatapi.cpp, src/megachatapi.h, src/megachatapi_impl.cpp, src/megachatapi_impl.h, src/net/websocketsIO.cpp, src/strongvelope/strongvelope.cpp, src/strongvelope/strongvelope.h, tests/sdk_test/sdk_test.cpp
Already merged into the release v2.3.2
=> Hotfix: #15019.Import new messages from a different cache #827 

bindings/java/nz/mega/sdk/MegaChatApiJava.java
This PR cannot be merged until https://github.com/meganz/android2/pull/1247 is.
=> Translated error strings. Android Bindings

src/chatd.h, src/rtcModule/webrtc.cpp, src/rtcModule/webrtcPrivate.h
If we are in a call and due a some missing Incall, we recieve an EndCall. If we aren't in a reconnection, we launch a new reconnection
=> #15279. Retry call when recieve our end call in some cases

bindings/Objective-C/MEGAChatSdk.h, src/chatd.cpp
Added already to `release/v2.3.4`
=>  Add authorizationToken parameter to firstname and lastname methods

tests/sdk_test/sdk_test.cpp, tests/sdk_test/sdk_test.h
Test modified:
- TEST_RichLinkUserAttribute
- TEST_SendRichLink
=> #15862. Use a request listener different for every call 

examples/megaclc/megaclc.cpp, src/megachatapi_impl.cpp, src/net/libwebsocketsIO.cpp
Also added the startUpload command
=> CHT-415. Update for building megaclc on windows without webrtc

src/megachatapi_impl.cpp
In this way, the local av change is notified in the right moment
=> CHT-430: Fire onChatCallUpdate at setCall when we set local av flags

src/megachatapi.h, src/megachatapi_impl.cpp
Merge this PR at the same time Webclient add this enhancement
=> CHT-428. Uncomment reactions limitations code
